import { StyleSheet } from 'react-native';

export const styles = StyleSheet.create({
    container: {
        flex: 1,
        backgroundColor: '#fff',
    },
    scrollView: {
        flex: 1,
    },
    header: {
        alignItems: 'center',
        paddingVertical: 30,
        borderBottomWidth: 1,
        borderBottomColor: '#FFA726',
        backgroundColor: '#fff',
        marginTop: 60,
    },
    headerTitle: {
        fontFamily: 'Nunito_700Bold',
        fontSize: 20,
        color: '#000',
    },
    backButton: {
        position: 'absolute',
        top: 20,
        left: 20,
        width: 44,
        height: 60,
        zIndex: 1,
        justifyContent: 'center',
        alignItems: 'center',
        backgroundColor: '#fff',
        borderRadius: 22,
    },
    userName: {
        fontFamily: 'Nunito_800ExtraBold',
        fontSize: 24,
        color: '#000',
        marginTop: 10,
    },
    userEmail: {
        fontFamily: 'Nunito_500Medium',
        fontSize: 16,
        color: '#666',
        marginTop: 5,
    },
    section: {
        padding: 20,
        backgroundColor: '#fffdf4',
    },
    sectionTitle: {
        fontFamily: 'Nunito_700Bold',
        fontSize: 20,
        color: '#000',
        marginBottom: 20,
    },
    optionContainer: {
        flexDirection: 'row',
        alignItems: 'center',
        justifyContent: 'space-between',
        backgroundColor: '#fff',
        padding: 15,
        borderRadius: 15,
        marginBottom: 15,
        borderWidth: 1,
        borderColor: '#FFA726',
    },
    optionButton: {
        flexDirection: 'row',
        alignItems: 'center',
        justifyContent: 'space-between',
        backgroundColor: '#fff',
        padding: 15,
        borderRadius: 15,
        marginBottom: 15,
        borderWidth: 1,
        borderColor: '#FFA726',
    },
    optionTextContainer: {
        flex: 1,
        marginRight: 10,
    },
    optionTitle: {
        fontFamily: 'Nunito_600SemiBold',
        fontSize: 16,
        color: '#000',
        marginBottom: 4,
    },
    optionDescription: {
        fontFamily: 'Nunito_500Medium',
        fontSize: 14,
        color: '#666',
    },
    signOutButton: {
        borderColor: '#FF5252',
        marginTop: 10,
    },
    signOutText: {
        color: '#FF5252',
    },
    infoContainer: {
        backgroundColor: '#fff',
        padding: 15,
        borderRadius: 15,
        marginBottom: 15,
        borderWidth: 1,
        borderColor: '#FFA726',
    },
    infoLabel: {
        fontFamily: 'Nunito_600SemiBold',
        fontSize: 14,
        color: '#666',
        marginBottom: 5,
    },
    infoValue: {
        fontFamily: 'Nunito_500Medium',
        fontSize: 16,
        color: '#000',
    },
    editButton: {
        backgroundColor: '#FFA726',
        margin: 20,
        padding: 15,
        borderRadius: 15,
        alignItems: 'center',
    },
    editButtonText: {
        fontFamily: 'Nunito_700Bold',
        fontSize: 16,
        color: '#fffdf4',
    },
    input: {
        backgroundColor: '#fff',
        borderRadius: 15,
        padding: 15,
        fontSize: 16,
        fontFamily: 'Nunito_500Medium',
        color: '#000',
        borderWidth: 1,
        borderColor: '#FFA726',
        width: '100%',
    },
    editButtonsContainer: {
        flexDirection: 'row',
        justifyContent: 'space-between',
        margin: 20,
    },
    cancelButton: {
        backgroundColor: '#666',
        flex: 1,
        marginRight: 10,
    },
    userTypeContainer: {
        marginTop: 0,
    },
    userTypeButtons: {
        flexDirection: 'row',
        justifyContent: 'space-between',
        gap: 10,
    },
    userTypeButton: {
        flex: 1,
        borderRadius: 15,
        padding: 15,
        alignItems: 'center',
        borderWidth: 1,
        borderColor: '#FFA726',
    },
    userTypeButtonActive: {
        backgroundColor: '#FFA726',
    },
    userTypeButtonText: {
        fontFamily: 'Nunito_600SemiBold',
        fontSize: 16,
        color: '#FFA726',
    },
    userTypeButtonTextActive: {
        color: '#fffdf4',
    },
}); 